title = "Gitleaks Configuration"

[allowlist]
  description = "Allowlisted patterns"
  condition = "AND"
  paths = [
    '''tests/''',
    '''examples/''',
  ]
  regexTarget = "match"
  regexes = [
    '''sonarcloud\.io/api/project_badges/measure\?project=.*&metric=''',
    '''codecov\.io/github/.*/graph/badge\.svg\?token=''',
  ]
